version: '3.7'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/app/src
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=dev